
package automa.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "automata", targetNamespace = "http://automa/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Automata {


    /**
     * 
     * @param fileName
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "download_file", partName = "download_file")
    public byte[] download(
        @WebParam(name = "file_name", partName = "file_name")
        String fileName);

    /**
     * 
     * @param fileName
     * @param bites
     */
    @WebMethod
    public void upload(
        @WebParam(name = "file_name", partName = "file_name")
        String fileName,
        @WebParam(name = "bites", partName = "bites")
        byte[] bites);

    /**
     * 
     * @param statesList
     * @param name
     * @return
     *     returns automa.model.Automa
     */
    @WebMethod
    @WebResult(name = "automata_from_param", partName = "automata_from_param")
    public Automa takeItParams(
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "states_list", partName = "states_list")
        StateArray statesList);

    /**
     * 
     * @param automa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string_automata", partName = "string_automata")
    public String takeAutomata(
        @WebParam(name = "automa", partName = "automa")
        Automa automa);

    /**
     * 
     * @return
     *     returns automa.model.Automa
     */
    @WebMethod
    @WebResult(name = "automata_default", partName = "automata_default")
    public Automa takeItDefault();

    /**
     * 
     * @param toHello
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "hello_message", partName = "hello_message")
    public String hello(
        @WebParam(name = "toHello", partName = "toHello")
        String toHello);

    /**
     * 
     * @param toHello
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "hello_message", partName = "hello_message")
    public String hello2(
        @WebParam(name = "toHello", partName = "toHello")
        String toHello);

    /**
     * 
     * @return
     *     returns automa.model.StateArray
     */
    @WebMethod
    @WebResult(name = "states_list", partName = "states_list")
    public StateArray takeStatesList();

}
